### ISSUE TITLE
[Suggestion] Integrate into a single custom app

### ISSUE THREAD

**Issue by harbassan** [Sowgro/legacyLibrary#2]
I wonder why you decided to create two custom apps for essentially a really similair idea (opening the library in the center pane). I like the main view of this one better, but i also think the sorting options available in the prior one (downloaded, by you) are also useful to have in the main view. I think it would be much better to put both apps into a single library app, with a simple settings menu to customise little things like this. It would also be easier for potential contributors. 

I can help you with the setting menu etc. by just copying the one i have in my custom app.

**Comment by Sowgro** [comment]
> I wonder why you decided to create two custom apps for essentially a really similair idea (opening the library in the center pane).

While on the surface it seems that these two custom apps do similar things, the implementation is significantly different. There is little shared code. 

> I like the main view of this one better, but i also think the sorting options available in the prior one (downloaded, by you) are also useful to have in the main view.

It sounds like you want something which is a mixture of the two libraries. This is a cool idea, but it is outside of the scope of this project. BetterLib and LegacyLib both are just working with the existing libraries created by Spotify. BetterLib temporarily moves the existing sidebar library into the main view, and LegacyLib provides a shortcut to the old library which is still present, but usually inaccessible. In neither app am I reconstructing, or even modifying either of the libraries.

> ...with a simple settings menu to customise little things like this.

I have thought about adding a settings menu to BetterLib, There are a few variables it would be nice for the user to control. I will possibly implement this in the future. 

I appreciate the question/suggestion, and I hope I cleared it up.
Feel free to contact me on discord `@sowgro`, I would be welcome to explain how the projects work in more detail.
